In [1]:
import numpy as np
import pandas as pd

In [2]:
customers = pd.read_csv("C:/POWER BI/09. Microsoft Power BI/Global+Electronics+Retailer/Customers.csv", encoding="latin1")
products = pd.read_csv("C:/POWER BI/09. Microsoft Power BI/Global+Electronics+Retailer/Products.csv", encoding="latin1")
sales = pd.read_csv("C:/POWER BI/09. Microsoft Power BI/Global+Electronics+Retailer/Sales.csv", encoding="latin1")
stores = pd.read_csv("C:/POWER BI/09. Microsoft Power BI/Global+Electronics+Retailer/Stores.csv", encoding="latin1")
exchange_rates = pd.read_csv("C:/POWER BI/09. Microsoft Power BI/Global+Electronics+Retailer/Exchange_Rates.csv", encoding="latin1")

### Customers Table

In [3]:
customers.head()

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
0,301,Female,Lilly Harding,WANDEARAH EAST,SA,South Australia,5523,Australia,Australia,7/3/1939
1,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Australia,9/27/1979
2,554,Female,Claire Ferres,WINJALLOK,VIC,Victoria,3380,Australia,Australia,5/26/1947
3,786,Male,Jai Poltpalingada,MIDDLE RIVER,SA,South Australia,5223,Australia,Australia,9/17/1957
4,1042,Male,Aidan Pankhurst,TAWONGA SOUTH,VIC,Victoria,3698,Australia,Australia,11/19/1965

In [4]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15266 entries, 0 to 15265
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerKey  15266 non-null  int64
 1   Gender       15266 non-null  object
 2   Name         15266 non-null  object
 3   City         15266 non-null  object
 4   State Code   15256 non-null  object
 5   State        15266 non-null  object
 6   Zip Code     15266 non-null  object
 7   Country      15266 non-null  object
 8   Continent    15266 non-null  object
 9   Birthday     15266 non-null  object
dtypes: int64(1), object(9)
memory usage: 1.2+ MB

- **Birthday wrong data type should be datetime**

In [5]:
customers.isnull().sum()

CustomerKey     0
Gender          0
Name            0
City            0
State Code     10
State           0
Zip Code        0
Country         0
Continent       0
Birthday        0
dtype: int64

- **10 missing value in State code**

In [6]:
print(customers.duplicated().sum())

0

In [7]:
customers["CustomerKey"].duplicated().sum()

np.int64(0)

In [8]:
customers["Gender"].value_counts()

Gender
Male      7748
Female    7518
Name: count, dtype: int64

In [9]:
customers["Country"].value_counts()

Country
United States     6828
United Kingdom    1944
Canada            1553
Germany           1473
Australia         1420
Netherlands        733
France             670
Italy              645
Name: count, dtype: int64

In [10]:
customers["Continent"].value_counts()

Continent
North America    8381
Europe           5465
Australia        1420
Name: count, dtype: int64

### Sales Table

In [11]:
sales.head()

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code
0,366000,1,1/1/2016,NaN,265598,10,1304,1,CAD
1,366001,1,1/1/2016,1/13/2016,1269051,0,1048,2,USD
2,366001,2,1/1/2016,1/13/2016,1269051,0,2007,1,USD
3,366002,1,1/1/2016,1/12/2016,266019,0,1106,7,CAD
4,366002,2,1/1/2016,1/12/2016,266019,0,373,1,CAD

In [12]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62884 entries, 0 to 62883
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order Number   62884 non-null  int64
 1   Line Item      62884 non-null  int64
 2   Order Date     62884 non-null  object
 3   Delivery Date  13165 non-null  object
 4   CustomerKey    62884 non-null  int64
 5   StoreKey       62884 non-null  int64
 6   ProductKey     62884 non-null  int64
 7   Quantity       62884 non-null  int64
 8   Currency Code  62884 non-null  object
dtypes: int64(6), object(3)
memory usage: 4.3+ MB

- **Order date and Delivery date Incorrect data type should be Datetime**

In [13]:
sales.isnull().sum()

Order Number         0
Line Item            0
Order Date           0
Delivery Date    49719
CustomerKey          0
StoreKey             0
ProductKey           0
Quantity             0
Currency Code        0
dtype: int64

- **Delivery date has **49719 missing** Value**

In [37]:
sales[sales["Delivery Date"].isnull()]

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code
0,366000,1,1/1/2016,NaN,265598,10,1304,1,CAD
6,366004,1,1/1/2016,NaN,1107461,38,163,6,GBP
7,366004,2,1/1/2016,NaN,1107461,38,1529,2,GBP
8,366005,1,1/1/2016,NaN,844003,33,421,4,EUR
9,366007,1,1/1/2016,NaN,2035771,43,1617,1,USD
...,...,...,...,...,...,...,...,...,...
62867,2243025,1,2/20/2021,NaN,1909290,49,1128,2,USD
62868,2243025,2,2/20/2021,NaN,1909290,49,2511,2,USD
62869,2243026,1,2/20/2021,NaN,1737466,49,58,6,USD
62872,2243028,1,2/20/2021,NaN,1728060,66,1584,3,USD
62879,2243030,1,2/20/2021,NaN,1216913,43,632,3,USD

In [14]:
sales.duplicated().sum()

np.int64(0)

In [15]:
sales["Currency Code"].value_counts()

Currency Code
USD    33767
EUR    12621
GBP     8140
CAD     5415
AUD     2941
Name: count, dtype: int64

In [16]:
sales[["Order Number","Line Item"]].duplicated().sum()

np.int64(0)

In [17]:
sales["Quantity"].describe()

count    62884.000000
mean         3.144790
std          2.256371
min          1.000000
25%          1.000000
50%          2.000000
75%          4.000000
max         10.000000
Name: Quantity, dtype: float64

In [18]:
sales[sales["Delivery Date"].isnull()]["StoreKey"].value_counts()

StoreKey
9     1577
50    1519
55    1518
54    1498
61    1485
59    1472
45    1471
57    1442
44    1436
65    1395
8     1360
51    1356
64    1353
47    1348
43    1340
66    1295
48    1289
56    1287
53    1284
10    1269
39    1054
40    1050
36    1049
49    1041
38    1034
42    1017
29    1011
37     995
30     976
63     948
5      892
22     800
62     778
27     721
24     703
23     674
19     635
6      615
33     498
32     454
34     448
41     444
20     443
4      431
31     417
21     391
26     295
1      292
15     235
12     224
16     214
28     214
17     210
18     194
13     184
14     126
2       18
Name: count, dtype: int64

In [19]:
sales[sales["Delivery Date"].notnull()]["StoreKey"].value_counts()

StoreKey
0    13165
Name: count, dtype: int64

### Store Table

In [20]:
stores.head()

   StoreKey    Country                         State  Square Meters  Open Date
0         1  Australia  Australian Capital Territory          595.0   1/1/2008
1         2  Australia            Northern Territory          665.0  1/12/2008
2         3  Australia               South Australia         2000.0   1/7/2012
3         4  Australia                      Tasmania         2000.0   1/1/2010
4         5  Australia                      Victoria         2000.0  12/9/2015

In [21]:
stores.tail()

    StoreKey        Country          State  Square Meters Open Date
62        63  United States           Utah         2000.0  3/6/2008
63        64  United States  Washington DC         1330.0  1/1/2010
64        65  United States  West Virginia         1785.0  1/1/2012
65        66  United States        Wyoming          840.0  1/1/2014
66         0         Online         Online            NaN  1/1/2010

In [22]:
stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   StoreKey       67 non-null     int64
 1   Country        67 non-null     object
 2   State          67 non-null     object
 3   Square Meters  66 non-null     float64
 4   Open Date      67 non-null     object
dtypes: float64(1), int64(1), object(3)
memory usage: 2.7+ KB

- **Open date Incorrect data type change it to Datetime**

In [23]:
stores.isnull().sum()

StoreKey         0
Country          0
State            0
Square Meters    1
Open Date        0
dtype: int64

- **One value is missing in the Square Meters becouse it is Online store so it is not an error**

In [24]:
stores.duplicated().sum()

np.int64(0)

In [25]:
stores["StoreKey"].duplicated().sum()

np.int64(0)

### - Product Table

In [26]:
products.head()

,ProductKey,Product Name,Brand,Color,Unit Cost USD,Unit Price USD,SubcategoryKey,Subcategory,CategoryKey,Category
0,1,Contoso 512MB MP3 Player E51 Silver,Contoso,Silver,$6.62,$12.99,101,MP4&MP3,1,Audio
1,2,Contoso 512MB MP3 Player E51 Blue,Contoso,Blue,$6.62,$12.99,101,MP4&MP3,1,Audio
2,3,Contoso 1G MP3 Player E100 White,Contoso,White,$7.40,$14.52,101,MP4&MP3,1,Audio
3,4,Contoso 2G MP3 Player E200 Silver,Contoso,Silver,$11.00,$21.57,101,MP4&MP3,1,Audio
4,5,Contoso 2G MP3 Player E200 Red,Contoso,Red,$11.00,$21.57,101,MP4&MP3,1,Audio

In [27]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2517 entries, 0 to 2516
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ProductKey      2517 non-null   int64
 1   Product Name    2517 non-null   object
 2   Brand           2517 non-null   object
 3   Color           2517 non-null   object
 4   Unit Cost USD   2517 non-null   object
 5   Unit Price USD  2517 non-null   object
 6   SubcategoryKey  2517 non-null   int64
 7   Subcategory     2517 non-null   object
 8   CategoryKey     2517 non-null   int64
 9   Category        2517 non-null   object
dtypes: int64(3), object(7)
memory usage: 196.8+ KB

- **Unit cost USD and Unit Price USD have douler sign becouse of this, this column have object datatype**

In [28]:
products.isnull().sum()

ProductKey        0
Product Name      0
Brand             0
Color             0
Unit Cost USD     0
Unit Price USD    0
SubcategoryKey    0
Subcategory       0
CategoryKey       0
Category          0
dtype: int64

In [29]:
products.duplicated().sum()

np.int64(0)

In [30]:
products["ProductKey"].duplicated().sum()

np.int64(0)

### Exchange Rate Table

In [31]:
exchange_rates.head()

       Date Currency  Exchange
0  1/1/2015      USD    1.0000
1  1/1/2015      CAD    1.1583
2  1/1/2015      AUD    1.2214
3  1/1/2015      EUR    0.8237
4  1/1/2015      GBP    0.6415

In [32]:
exchange_rates.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11215 entries, 0 to 11214
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      11215 non-null  object
 1   Currency  11215 non-null  object
 2   Exchange  11215 non-null  float64
dtypes: float64(1), object(2)
memory usage: 263.0+ KB

- **Date Incorrect Data type should be Datetime**

In [33]:
exchange_rates.isnull().sum()

Date        0
Currency    0
Exchange    0
dtype: int64

In [34]:
exchange_rates.duplicated().sum()

np.int64(0)